version: '2'
services:
  # Selenium chrome
  selenium-chrome:
    image: "selenium/standalone-chrome"

  # Pytest
  pytest:
    build: ./loginapp
    command: ./run_pytest.sh
    volumes:
      - ./loginapp:/app
    depends_on:
      - selenium-chrome
      - web
