version: '2'
services:

  # PostgreSQL database
  db:
    image: postgres

  # Redis
  redis:
    image: "redis:alpine"

  # Django web server
  web:
    build: ./loginapp
    command: ./run_web.sh # python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./loginapp:/app
    ports:
      - "8000:8000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  # Celery worker
  worker:
    build: ./loginapp
    command: ./run_celery.sh
    volumes:
      - ./loginapp:/app
    links:
      - db
      - redis
    depends_on:
      - db
      - redis