version: '2'
services:
  db:
    image: postgres
  redis:
    image: "redis:alpine"
  web:
    build: ./loginapp
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./loginapp:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis