version: '2'
services:
  # PostgreSQL database
  db:
    image: postgres

  # Redis
  redis:
    image: "redis:alpine"

  # Django web server
  web:
    build: ./loginapp
    command: ./run_web.sh
    volumes:
      - ./loginapp:/app
    ports:
      - "8000:8000"
      - "8081:8081"
    depends_on:
      - db
      - redis

  # Celery worker
  worker:
    build: ./loginapp
    command: ./run_celery.sh
    volumes:
      - ./loginapp:/app
    depends_on:
      - db
      - redis